In [53]:
import pandas as pd
import numpy as np

In [54]:
tag_data = pd.read_csv("/w/225/1/chess/tactics/tag_data_updated.csv")

In [55]:
num_of_rows, num_of_cols = tag_data.shape
new_tag_data = pd.DataFrame(index = np.arange(num_of_rows), columns = ['Puzzle ID', 'Tag'])
new_tag_data['Puzzle ID'] = tag_data['tactics_problem_id']
new_tag_data

       Puzzle ID  Tag
0            731  NaN
1            732  NaN
2            738  NaN
3            739  NaN
4            740  NaN
...          ...  ...
54801     661058  NaN
54802     661060  NaN
54803     661062  NaN
54804     661064  NaN
54805     661066  NaN

[54806 rows x 2 columns]

In [56]:
temp = tag_data.drop(columns = ['tactics_problem_id','Unnamed: 0', 'average_seconds', 'move_count'])
temp

,Attacking f7/f2,Attacking Castled King,Back Rank,Basic Checkmates,Exchange Sacrifice,Mate in 3+,Mating Net,Queen Sacrifice,Sacrifice,Vulnerable King,...,Endgame Tactics,Stalemate,Perpetual Check,Desperado,Zugzwang,En passant,Windmill,Underpromotion,Double,Opposition
0,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,True,True,False,True,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54801,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54802,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54803,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54804,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54805,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [57]:
tag_data

,Unnamed: 0,tactics_problem_id,average_seconds,move_count,Attacking f7/f2,Attacking Castled King,Back Rank,Basic Checkmates,Exchange Sacrifice,Mate in 3+,...,Endgame Tactics,Stalemate,Perpetual Check,Desperado,Zugzwang,En passant,Windmill,Underpromotion,Double,Opposition
0,1,731,41,3,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1,2,732,26,2,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3,738,54,3,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,4,739,57,3,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
4,5,740,88,5,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54801,54802,661058,84,4,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
54802,54803,661060,88,2,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54803,54804,661062,38,2,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54804,54805,661064,65,3,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54805,54806,661066,81,3,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [58]:
count_true_tag = {}
key_to_tag = {}
ind = 0
for col in temp.columns:
    count_true_tag[ind] = len(temp[temp[col] == True])
    key_to_tag[ind] = col
    ind = ind + 1

In [59]:
row,col = tag_data.shape
for i in range(row):
    tags_list = np.array(temp.iloc[i,:])
    indices = np.nonzero(tags_list)
    minimum = count_true_tag[indices[0][0]]
    key = indices[0][0]
    for j in range(1, len(indices)):
        count_true = count_true_tag[indices[0][j]]
        if count_true < minimum:
            key = indices[0][j]
            minimum = count_true
    new_tag_data.iloc[i,1] = key_to_tag[key]

In [60]:
new_tag_data.to_csv('single_tag_data.csv')